### ISSUE TITLE
"Edit Item" in Public Site Not Working

### ISSUE THREAD

**Issue by urentmellc** [pixelphpdev/urentme#8]

**Comment by pxlsz** [comment]
Done this issue.

**Comment by urentmellc** [comment]
stated done what was completed? What was the issue?

**Comment by Jayantapixel** [comment]
We have already discussed on it. The issues was, in make, model etc instead of value its calling field ID so its showing as numeric. Its already corrected. So please check and close this issue.

**Comment by urentmellc** [comment]
![editlistingstillanissue](https://user-images.githubusercontent.com/34143768/37177220-a407552e-22d3-11e8-827c-2cd461cd0517.jpeg)

still an issue with the code, does not allow you to go to the next screen shows as an error in red, dont need to edit that screen why re enter new data? This will irritate people. Please fix so you can edit next pages without requiring the current incorrect system. This is not good. Not fixed... Please fix asap.

**Comment by Jayantapixel** [comment]
We have reviewed the code and found its not an issue rather a feature in your application. The developer has integrated Google Geo Location API to validate the address. Its taking Address, City, State and Pin and checking in Google API if its has any proper Latitude/Longitude. If its available then its saving otherwise throwing this error. This will prevent to add any bad data in database. If you don't want that, let me know so we can remove that validation and API will not work. This will require some time to remove the same.

**Comment by urentmellc** [comment]
this is not normal to happen this way, I dont want to deal with seeing that everytime I edit... I need to keep the google api. Please fix or advise accordingly.

**Comment by Jayantapixel** [comment]
If you keep the Google API for validation then the address should match with Google API Latitude Longitude. We cant change on their API. Alternatively, we need to remove that API. In general we dont use Google API for full address checking unless its a location specific site. You decide pls.

**Comment by urentmellc** [comment]
Hi do you suggest we remove it? How will it affect our site and address entries etc?

 

Anthony HorovitzFounder, URentMe.Com855-400-0082 | 702-219-0186 | anthony@urentme.com | www.urentme.com | Skype: anthony.horovitz | 871 Coronado Center Drive, Suite 200, Henderson, NV 89052

**Comment by Jayantapixel** [comment]
I have already written in my comments that only the bad data will be saved in database if we remove that API validation. AND if you want keep that then it will prevent to put wrong matching of address. That's very simple. But if you want to keep that but don't want to get error putting wrong matching, then its simple not possible.

**Comment by pxlsz** [comment]
Please reply or close it if its OK.

**Comment by Jayantapixel** [comment]
I found, since the Google API is free which used in the site, so its causing problem sometime when I am trying to edit the item I entered. I would suggest to remove it. Please confirm, so developer can remove on Monday.

**Comment by urentmellc** [comment]
We need google api to show the map location please fix this code issue so it works asap. Thank you. Or find another way to show the map this needs to be used as its part of our service.

**Comment by urentmellc** [comment]
Hi jayanta.. We need google api to show the map location please fix this code issue so it works asap. Thank you. Or find another way to show the map this needs to be used as its part of our service. This needs to be fixed your Monday am please.
Top of Form

Bottom of Form

 

 

 

Anthony HorovitzFounder, URentMe.Com855-400-0082 | 702-219-0186 | anthony@urentme.com | www.urentme.com | Skype: anthony.horovitz | 871 Coronado Center Drive, Suite 200, Henderson, NV 89052

**Comment by Jayantapixel** [comment]
I feel you need to take paid version of the API. I will let you know on Monday.
